name: ultimate_flutter_icons
description: "This package allows you to use a lot of icons from a lot of different sources. It is based on the react project: react-icons"
version: 1.0.4
homepage: https://github.com/salusinco/flutter_icons
repository: https://github.com/salusinco/flutter_icons

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

