name: Build and publish

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: 'Checkout'
      uses: actions/checkout@main
    -
      name: Build with bun
      uses: oven-sh/setup-bun@v1
    - run: bun i
    - run: time(cd build && bun run build)
    - 
      name: 'Publishing to pub'
      uses: k-paxian/dart-package-publisher@master
      with:
        accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
        refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
